name = [1,'2',3,'34']
print(name[0:2])
print(name[:2])
print(name[:])
del name[1]
print(name)
print(len(name))
name1=[1,2,3,2,1,3,12,312,121]
print(max(name1))
print(name1)
print(min(name1)) 
print(name1.append(1))       
print(name1)
print(name1.count(1))        
print(name1)
print(name1.extend([1,2,3]))       
print(name1)
print(name1.index(3))        
print(name1)
print(name1.pop()) 
print(name1)
print(name1.remove(1))       
print(name1)
print(name1.reverse())         
print(name1)
print(name1.insert(1,"nihao"))
print(name1)
